name: acab_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  google_fonts: ^1.1.1
  sqflite: any
  path_provider: any
  intl: ^0.16.1
  http: any
  flutter_spinkit: "^4.1.2"
  excel: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/excel/
